import { CountryModel } from '../models/country.model';

const countries = [
    { name: 'Afghanistan', alphaCode2: 'AF', alphaCode3: 'AFG' },
    { name: 'Åland Islands', alphaCode2: 'AX', alphaCode3: 'ALA' },
    { name: 'Albania', alphaCode2: 'AL', alphaCode3: 'ALB' },
    { name: 'Algeria', alphaCode2: 'DZ', alphaCode3: 'DZA' },
    { name: 'American Samoa', alphaCode2: 'AS', alphaCode3: 'ASM' },
    { name: 'Andorra', alphaCode2: 'AD', alphaCode3: 'AND' },
    { name: 'Angola', alphaCode2: 'AO', alphaCode3: 'AGO' },
    { name: 'Anguilla', alphaCode2: 'AI', alphaCode3: 'AIA' },
    { name: 'Antarctica', alphaCode2: 'AQ', alphaCode3: 'ATA' },
    { name: 'Antigua and Barbuda', alphaCode2: 'AG', alphaCode3: 'ATG' },
    { name: 'Argentina', alphaCode2: 'AR', alphaCode3: 'ARG' },
    { name: 'Armenia', alphaCode2: 'AM', alphaCode3: 'ARM' },
    { name: 'Aruba', alphaCode2: 'AW', alphaCode3: 'ABW' },
    { name: 'Australia', alphaCode2: 'AU', alphaCode3: 'AUS' },
    { name: 'Austria', alphaCode2: 'AT', alphaCode3: 'AUT' },
    { name: 'Azerbaijan', alphaCode2: 'AZ', alphaCode3: 'AZE' },
    { name: 'Bahamas', alphaCode2: 'BS', alphaCode3: 'BHS' },
    { name: 'Bahrain', alphaCode2: 'BH', alphaCode3: 'BHR' },
    { name: 'Bangladesh', alphaCode2: 'BD', alphaCode3: 'BGD' },
    { name: 'Barbados', alphaCode2: 'BB', alphaCode3: 'BRB' },
    { name: 'Belarus', alphaCode2: 'BY', alphaCode3: 'BLR' },
    { name: 'Belgium', alphaCode2: 'BE', alphaCode3: 'BEL' },
    { name: 'Belize', alphaCode2: 'BZ', alphaCode3: 'BLZ' },
    { name: 'Benin', alphaCode2: 'BJ', alphaCode3: 'BEN' },
    { name: 'Bermuda', alphaCode2: 'BM', alphaCode3: 'BMU' },
    { name: 'Bhutan', alphaCode2: 'BT', alphaCode3: 'BTN' },
    { name: 'Bolivia (Plurinational State of)', alphaCode2: 'BO', alphaCode3: 'BOL' },
    { name: 'Bonaire Sint Eustatius Saba', alphaCode2: 'BQ', alphaCode3: 'BES' },
    { name: 'Bosnia and Herzegovina', alphaCode2: 'BA', alphaCode3: 'BIH' },
    { name: 'Botswana', alphaCode2: 'BW', alphaCode3: 'BWA' },
    { name: 'Bouvet Island', alphaCode2: 'BV', alphaCode3: 'BVT' },
    { name: 'Brazil', alphaCode2: 'BR', alphaCode3: 'BRA' },
    { name: 'British Indian Ocean Territory', alphaCode2: 'IO', alphaCode3: 'IOT' },
    { name: 'Brunei Darussalam', alphaCode2: 'BN', alphaCode3: 'BRN' },
    { name: 'Bulgaria', alphaCode2: 'BG', alphaCode3: 'BGR' },
    { name: 'Burkina Faso', alphaCode2: 'BF', alphaCode3: 'BFA' },
    { name: 'Burundi', alphaCode2: 'BI', alphaCode3: 'BDI' },
    { name: 'Cabo Verde', alphaCode2: 'CV', alphaCode3: 'CPV' },
    { name: 'Cambodia', alphaCode2: 'KH', alphaCode3: 'KHM' },
    { name: 'Cameroon', alphaCode2: 'CM', alphaCode3: 'CMR' },
    { name: 'Canada', alphaCode2: 'CA', alphaCode3: 'CAN' },
    { name: 'Cayman Islands', alphaCode2: 'KY', alphaCode3: 'CYM' },
    { name: 'Central African Republic', alphaCode2: 'CF', alphaCode3: 'CAF' },
    { name: 'Chad', alphaCode2: 'TD', alphaCode3: 'TCD' },
    { name: 'Chile', alphaCode2: 'CL', alphaCode3: 'CHL' },
    { name: 'China', alphaCode2: 'CN', alphaCode3: 'CHN' },
    { name: 'Christmas Island', alphaCode2: 'CX', alphaCode3: 'CXR' },
    { name: 'Cocos (Keeling) Islands', alphaCode2: 'CC', alphaCode3: 'CCK' },
    { name: 'Colombia', alphaCode2: 'CO', alphaCode3: 'COL' },
    { name: 'Comoros', alphaCode2: 'KM', alphaCode3: 'COM' },
    { name: 'Congo (the Democratic Republic of the)', alphaCode2: 'CD', alphaCode3: 'COD' },
    { name: 'Congo', alphaCode2: 'CG', alphaCode3: 'COG' },
    { name: 'Cook Islands', alphaCode2: 'CK', alphaCode3: 'COK' },
    { name: 'Costa Rica', alphaCode2: 'CR', alphaCode3: 'CRI' },
    {
        name: 'Côte d\'Ivoire', alphaCode2: 'CI', alphaCode3: 'CIV'
    },
    { name: 'Croatia', alphaCode2: 'HR', alphaCode3: 'HRV' },
    { name: 'Cuba', alphaCode2: 'CU', alphaCode3: 'CUB' },
    { name: 'Curaçao', alphaCode2: 'CW', alphaCode3: 'CUW' },
    { name: 'Cyprus', alphaCode2: 'CY', alphaCode3: 'CYP' },
    { name: 'Czechia', alphaCode2: 'CZ', alphaCode3: 'CZE' },
    { name: 'Denmark', alphaCode2: 'DK', alphaCode3: 'DNK' },
    { name: 'Djibouti', alphaCode2: 'DJ', alphaCode3: 'DJI' },
    { name: 'Dominica', alphaCode2: 'DM', alphaCode3: 'DMA' },
    { name: 'Dominican Republic', alphaCode2: 'DO', alphaCode3: 'DOM' },
    { name: 'Ecuador', alphaCode2: 'EC', alphaCode3: 'ECU' },
    { name: 'Egypt', alphaCode2: 'EG', alphaCode3: 'EGY' },
    { name: 'El Salvador', alphaCode2: 'SV', alphaCode3: 'SLV' },
    { name: 'Equatorial Guinea', alphaCode2: 'GQ', alphaCode3: 'GNQ' },
    { name: 'Eritrea', alphaCode2: 'ER', alphaCode3: 'ERI' },
    { name: 'Estonia', alphaCode2: 'EE', alphaCode3: 'EST' },
    { name: 'Eswatini', alphaCode2: 'SZ', alphaCode3: 'SWZ' },
    { name: 'Ethiopia', alphaCode2: 'ET', alphaCode3: 'ETH' },
    { name: 'Falkland Islands [Malvinas]', alphaCode2: 'FK', alphaCode3: 'FLK' },
    { name: 'Faroe Islands', alphaCode2: 'FO', alphaCode3: 'FRO' },
    { name: 'Fiji', alphaCode2: 'FJ', alphaCode3: 'FJI' },
    { name: 'Finland', alphaCode2: 'FI', alphaCode3: 'FIN' },
    { name: 'France', alphaCode2: 'FR', alphaCode3: 'FRA' },
    { name: 'French Guiana', alphaCode2: 'GF', alphaCode3: 'GUF' },
    { name: 'French Polynesia', alphaCode2: 'PF', alphaCode3: 'PYF' },
    { name: 'French Southern Territories', alphaCode2: 'TF', alphaCode3: 'ATF' },
    { name: 'Gabon', alphaCode2: 'GA', alphaCode3: 'GAB' },
    { name: 'Gambia', alphaCode2: 'GM', alphaCode3: 'GMB' },
    { name: 'Georgia', alphaCode2: 'GE', alphaCode3: 'GEO' },
    { name: 'Germany', alphaCode2: 'DE', alphaCode3: 'DEU' },
    { name: 'Ghana', alphaCode2: 'GH', alphaCode3: 'GHA' },
    { name: 'Gibraltar', alphaCode2: 'GI', alphaCode3: 'GIB' },
    { name: 'Greece', alphaCode2: 'GR', alphaCode3: 'GRC' },
    { name: 'Greenland', alphaCode2: 'GL', alphaCode3: 'GRL' },
    { name: 'Grenada', alphaCode2: 'GD', alphaCode3: 'GRD' },
    { name: 'Guadeloupe', alphaCode2: 'GP', alphaCode3: 'GLP' },
    { name: 'Guam', alphaCode2: 'GU', alphaCode3: 'GUM' },
    { name: 'Guatemala', alphaCode2: 'GT', alphaCode3: 'GTM' },
    { name: 'Guernsey', alphaCode2: 'GG', alphaCode3: 'GGY' },
    { name: 'Guinea', alphaCode2: 'GN', alphaCode3: 'GIN' },
    { name: 'Guinea-Bissau', alphaCode2: 'GW', alphaCode3: 'GNB' },
    { name: 'Guyana', alphaCode2: 'GY', alphaCode3: 'GUY' },
    { name: 'Haiti', alphaCode2: 'HT', alphaCode3: 'HTI' },
    { name: 'Heard Island and McDonald Islands', alphaCode2: 'HM', alphaCode3: 'HMD' },
    { name: 'Holy See', alphaCode2: 'VA', alphaCode3: 'VAT' },
    { name: 'Honduras', alphaCode2: 'HN', alphaCode3: 'HND' },
    { name: 'Hong Kong', alphaCode2: 'HK', alphaCode3: 'HKG' },
    { name: 'Hungary', alphaCode2: 'HU', alphaCode3: 'HUN' },
    { name: 'Iceland', alphaCode2: 'IS', alphaCode3: 'ISL' },
    { name: 'India', alphaCode2: 'IN', alphaCode3: 'IND' },
    { name: 'Indonesia', alphaCode2: 'ID', alphaCode3: 'IDN' },
    { name: 'Iran (Islamic Republic of)', alphaCode2: 'IR', alphaCode3: 'IRN' },
    { name: 'Iraq', alphaCode2: 'IQ', alphaCode3: 'IRQ' },
    { name: 'Ireland', alphaCode2: 'IE', alphaCode3: 'IRL' },
    { name: 'Isle of Man', alphaCode2: 'IM', alphaCode3: 'IMN' },
    { name: 'Israel', alphaCode2: 'IL', alphaCode3: 'ISR' },
    { name: 'Italy', alphaCode2: 'IT', alphaCode3: 'ITA' },
    { name: 'Jamaica', alphaCode2: 'JM', alphaCode3: 'JAM' },
    { name: 'Japan', alphaCode2: 'JP', alphaCode3: 'JPN' },
    { name: 'Jersey', alphaCode2: 'JE', alphaCode3: 'JEY' },
    { name: 'Jordan', alphaCode2: 'JO', alphaCode3: 'JOR' },
    { name: 'Kazakhstan', alphaCode2: 'KZ', alphaCode3: 'KAZ' },
    { name: 'Kenya', alphaCode2: 'KE', alphaCode3: 'KEN' },
    { name: 'Kiribati', alphaCode2: 'KI', alphaCode3: 'KIR' },
    { name: 'Korea', alphaCode2: 'KR', alphaCode3: 'KOR' },
    { name: 'Kuwait', alphaCode2: 'KW', alphaCode3: 'KWT' },
    { name: 'Kyrgyzstan', alphaCode2: 'KG', alphaCode3: 'KGZ' },
    { name: 'Lao People\'s Democratic Republic', alphaCode2: 'LA', alphaCode3: 'LAO' },
    { name: 'Latvia', alphaCode2: 'LV', alphaCode3: 'LVA' },
    { name: 'Lebanon', alphaCode2: 'LB', alphaCode3: 'LBN' },
    { name: 'Lesotho', alphaCode2: 'LS', alphaCode3: 'LSO' },
    { name: 'Liberia', alphaCode2: 'LR', alphaCode3: 'LBR' },
    { name: 'Libya', alphaCode2: 'LY', alphaCode3: 'LBY' },
    { name: 'Liechtenstein', alphaCode2: 'LI', alphaCode3: 'LIE' },
    { name: 'Lithuania', alphaCode2: 'LT', alphaCode3: 'LTU' },
    { name: 'Luxembourg', alphaCode2: 'LU', alphaCode3: 'LUX' },
    { name: 'Macao', alphaCode2: 'MO', alphaCode3: 'MAC' },
    { name: 'North Macedonia', alphaCode2: 'MK', alphaCode3: 'MKD' },
    { name: 'Madagascar', alphaCode2: 'MG', alphaCode3: 'MDG' },
    { name: 'Malawi', alphaCode2: 'MW', alphaCode3: 'MWI' },
    { name: 'Malaysia', alphaCode2: 'MY', alphaCode3: 'MYS' },
    { name: 'Maldives', alphaCode2: 'MV', alphaCode3: 'MDV' },
    { name: 'Mali', alphaCode2: 'ML', alphaCode3: 'MLI' },
    { name: 'Malta', alphaCode2: 'MT', alphaCode3: 'MLT' },
    { name: 'Marshall Islands', alphaCode2: 'MH', alphaCode3: 'MHL' },
    { name: 'Martinique', alphaCode2: 'MQ', alphaCode3: 'MTQ' },
    { name: 'Mauritania', alphaCode2: 'MR', alphaCode3: 'MRT' },
    { name: 'Mauritius', alphaCode2: 'MU', alphaCode3: 'MUS' },
    { name: 'Mayotte', alphaCode2: 'YT', alphaCode3: 'MYT' },
    { name: 'Mexico', alphaCode2: 'MX', alphaCode3: 'MEX' },
    { name: 'Micronesia (Federated States of)', alphaCode2: 'FM', alphaCode3: 'FSM' },
    { name: 'Moldova', alphaCode2: 'MD', alphaCode3: 'MDA' },
    { name: 'Monaco', alphaCode2: 'MC', alphaCode3: 'MCO' },
    { name: 'Mongolia', alphaCode2: 'MN', alphaCode3: 'MNG' },
    { name: 'Montenegro', alphaCode2: 'ME', alphaCode3: 'MNE' },
    { name: 'Montserrat', alphaCode2: 'MS', alphaCode3: 'MSR' },
    { name: 'Morocco', alphaCode2: 'MA', alphaCode3: 'MAR' },
    { name: 'Mozambique', alphaCode2: 'MZ', alphaCode3: 'MOZ' },
    { name: 'Myanmar', alphaCode2: 'MM', alphaCode3: 'MMR' },
    { name: 'Namibia', alphaCode2: 'NA', alphaCode3: 'NAM' },
    { name: 'Nauru', alphaCode2: 'NR', alphaCode3: 'NRU' },
    { name: 'Nepal', alphaCode2: 'NP', alphaCode3: 'NPL' },
    { name: 'Netherlands', alphaCode2: 'NL', alphaCode3: 'NLD' },
    { name: 'New Caledonia', alphaCode2: 'NC', alphaCode3: 'NCL' },
    { name: 'New Zealand', alphaCode2: 'NZ', alphaCode3: 'NZL' },
    { name: 'Nicaragua', alphaCode2: 'NI', alphaCode3: 'NIC' },
    { name: 'Niger', alphaCode2: 'NE', alphaCode3: 'NER' },
    { name: 'Nigeria', alphaCode2: 'NG', alphaCode3: 'NGA' },
    { name: 'Niue', alphaCode2: 'NU', alphaCode3: 'NIU' },
    { name: 'Norfolk Island', alphaCode2: 'NF', alphaCode3: 'NFK' },
    { name: 'Northern Mariana Islands', alphaCode2: 'MP', alphaCode3: 'MNP' },
    { name: 'Norway', alphaCode2: 'NO', alphaCode3: 'NOR' },
    { name: 'Oman', alphaCode2: 'OM', alphaCode3: 'OMN' },
    { name: 'Pakistan', alphaCode2: 'PK', alphaCode3: 'PAK' },
    { name: 'Palau', alphaCode2: 'PW', alphaCode3: 'PLW' },
    { name: 'Palestine, State of', alphaCode2: 'PS', alphaCode3: 'PSE' },
    { name: 'Panama', alphaCode2: 'PA', alphaCode3: 'PAN' },
    { name: 'Papua New Guinea', alphaCode2: 'PG', alphaCode3: 'PNG' },
    { name: 'Paraguay', alphaCode2: 'PY', alphaCode3: 'PRY' },
    { name: 'Peru', alphaCode2: 'PE', alphaCode3: 'PER' },
    { name: 'Philippines', alphaCode2: 'PH', alphaCode3: 'PHL' },
    { name: 'Pitcairn', alphaCode2: 'PN', alphaCode3: 'PCN' },
    { name: 'Poland', alphaCode2: 'PL', alphaCode3: 'POL' },
    { name: 'Portugal', alphaCode2: 'PT', alphaCode3: 'PRT' },
    { name: 'Puerto Rico', alphaCode2: 'PR', alphaCode3: 'PRI' },
    { name: 'Qatar', alphaCode2: 'QA', alphaCode3: 'QAT' },
    { name: 'Réunion', alphaCode2: 'RE', alphaCode3: 'REU' },
    { name: 'Romania', alphaCode2: 'RO', alphaCode3: 'ROU' },
    { name: 'Russian Federation', alphaCode2: 'RU', alphaCode3: 'RUS' },
    { name: 'Rwanda', alphaCode2: 'RW', alphaCode3: 'RWA' },
    { name: 'Saint Barthélemy', alphaCode2: 'BL', alphaCode3: 'BLM' },
    { name: 'Saint Helena Ascension Island Tristan da Cunha', alphaCode2: 'SH', alphaCode3: 'SHN' },
    { name: 'Saint Kitts and Nevis', alphaCode2: 'KN', alphaCode3: 'KNA' },
    { name: 'Saint Lucia', alphaCode2: 'LC', alphaCode3: 'LCA' },
    { name: 'Saint Martin (French part)', alphaCode2: 'MF', alphaCode3: 'MAF' },
    { name: 'Saint Pierre and Miquelon', alphaCode2: 'PM', alphaCode3: 'SPM' },
    { name: 'Saint Vincent and the Grenadines', alphaCode2: 'VC', alphaCode3: 'VCT' },
    { name: 'Samoa', alphaCode2: 'WS', alphaCode3: 'WSM' },
    { name: 'San Marino', alphaCode2: 'SM', alphaCode3: 'SMR' },
    { name: 'Sao Tome and Principe', alphaCode2: 'ST', alphaCode3: 'STP' },
    { name: 'Saudi Arabia', alphaCode2: 'SA', alphaCode3: 'SAU' },
    { name: 'Senegal', alphaCode2: 'SN', alphaCode3: 'SEN' },
    { name: 'Serbia', alphaCode2: 'RS', alphaCode3: 'SRB' },
    { name: 'Seychelles', alphaCode2: 'SC', alphaCode3: 'SYC' },
    { name: 'Sierra Leone', alphaCode2: 'SL', alphaCode3: 'SLE' },
    { name: 'Singapore', alphaCode2: 'SG', alphaCode3: 'SGP' },
    { name: 'Sint Maarten (Dutch part)', alphaCode2: 'SX', alphaCode3: 'SXM' },
    { name: 'Slovakia', alphaCode2: 'SK', alphaCode3: 'SVK' },
    { name: 'Slovenia', alphaCode2: 'SI', alphaCode3: 'SVN' },
    { name: 'Solomon Islands', alphaCode2: 'SB', alphaCode3: 'SLB' },
    { name: 'Somalia', alphaCode2: 'SO', alphaCode3: 'SOM' },
    { name: 'South Africa', alphaCode2: 'ZA', alphaCode3: 'ZAF' },
    { name: 'South Georgia and the South Sandwich Islands', alphaCode2: 'GS', alphaCode3: 'SGS' },
    { name: 'South Sudan', alphaCode2: 'SS', alphaCode3: 'SSD' },
    { name: 'Spain', alphaCode2: 'ES', alphaCode3: 'ESP' },
    { name: 'Sri Lanka', alphaCode2: 'LK', alphaCode3: 'LKA' },
    { name: 'Sudan', alphaCode2: 'SD', alphaCode3: 'SDN' },
    { name: 'Suriname', alphaCode2: 'SR', alphaCode3: 'SUR' },
    { name: 'Svalbard Jan Mayen', alphaCode2: 'SJ', alphaCode3: 'SJM' },
    { name: 'Sweden', alphaCode2: 'SE', alphaCode3: 'SWE' },
    { name: 'Switzerland', alphaCode2: 'CH', alphaCode3: 'CHE' },
    { name: 'Syrian Arab Republic', alphaCode2: 'SY', alphaCode3: 'SYR' },
    { name: 'Taiwan (Province of China)', alphaCode2: 'TW', alphaCode3: 'TWN' },
    { name: 'Tajikistan', alphaCode2: 'TJ', alphaCode3: 'TJK' },
    { name: 'Tanzania, the United Republic of', alphaCode2: 'TZ', alphaCode3: 'TZA' },
    { name: 'Thailand', alphaCode2: 'TH', alphaCode3: 'THA' },
    { name: 'Timor-Leste', alphaCode2: 'TL', alphaCode3: 'TLS' },
    { name: 'Togo', alphaCode2: 'TG', alphaCode3: 'TGO' },
    { name: 'Tokelau', alphaCode2: 'TK', alphaCode3: 'TKL' },
    { name: 'Tonga', alphaCode2: 'TO', alphaCode3: 'TON' },
    { name: 'Trinidad and Tobago', alphaCode2: 'TT', alphaCode3: 'TTO' },
    { name: 'Tunisia', alphaCode2: 'TN', alphaCode3: 'TUN' },
    { name: 'Turkey', alphaCode2: 'TR', alphaCode3: 'TUR' },
    { name: 'Turkmenistan', alphaCode2: 'TM', alphaCode3: 'TKM' },
    { name: 'Turks and Caicos Islands', alphaCode2: 'TC', alphaCode3: 'TCA' },
    { name: 'Tuvalu', alphaCode2: 'TV', alphaCode3: 'TUV' },
    { name: 'Uganda', alphaCode2: 'UG', alphaCode3: 'UGA' },
    { name: 'Ukraine', alphaCode2: 'UA', alphaCode3: 'UKR' },
    { name: 'United Arab Emirates', alphaCode2: 'AE', alphaCode3: 'ARE' },
    { name: 'United Kingdom of Great Britain and Northern Ireland', alphaCode2: 'GB', alphaCode3: 'GBR' },
    { name: 'United States Minor Outlying Islands', alphaCode2: 'UM', alphaCode3: 'UMI' },
    { name: 'United States of America', alphaCode2: 'US', alphaCode3: 'USA' },
    { name: 'Uruguay', alphaCode2: 'UY', alphaCode3: 'URY' },
    { name: 'Uzbekistan', alphaCode2: 'UZ', alphaCode3: 'UZB' },
    { name: 'Vanuatu', alphaCode2: 'VU', alphaCode3: 'VUT' },
    { name: 'Venezuela (Bolivarian Republic of)', alphaCode2: 'VE', alphaCode3: 'VEN' },
    { name: 'Viet Nam', alphaCode2: 'VN', alphaCode3: 'VNM' },
    { name: 'Virgin Islands (British)', alphaCode2: 'VG', alphaCode3: 'VGB' },
    { name: 'Virgin Islands (U.S.)', alphaCode2: 'VI', alphaCode3: 'VIR' },
    { name: 'Wallis and Futuna', alphaCode2: 'WF', alphaCode3: 'WLF' },
    { name: 'Western Sahara', alphaCode2: 'EH', alphaCode3: 'ESH' },
    { name: 'Yemen', alphaCode2: 'YE', alphaCode3: 'YEM' },
    { name: 'Zambia', alphaCode2: 'ZM', alphaCode3: 'ZMB' },
    { name: 'Zimbabwe', alphaCode2: 'ZW', alphaCode3: 'ZWE' }]

const docs = [
    { countryId: 'BRA', name: 'Brazil', webId: 'BR', latitude: -10, longitude: -55 },
    { countryId: 'CHN', name: 'China', webId: 'CN', latitude: 35, longitude: 105 },
    { countryId: 'FRA', name: 'France', webId: 'FR', latitude: 47, longitude: 2 },
    { countryId: 'IND', name: 'India', webId: 'IN', latitude: 28.47, longitude: 77.03 },
    { countryId: 'USA', name: 'USA', webId: 'US', latitude: 38, longitude: -97 }
];

CountryModel.insertMany(countries, (err, docs) => {
    if (err) {
        console.error('CountryModel.insertMany: Failed', err);
        return false;
    }
    console.log('%d Countries added successfully!!!', docs.length);
});

/* CountryModel
    .find()
    .then(docs => {
        console.log(docs);
    })
    .catch(error => {
        console.log(error);
    }); */