import { StateModel } from '../models/state.model';

const docs = [
    { stateId: 5, name: 'California', countryId: 'USA' },
    { stateId: 6, name: 'Beijing', countryId: 'CHN' },
    { stateId: 9, name: 'Iowa', countryId: 'USA' },
    { stateId: 10, name: 'New York', countryId: 'USA' },
    { stateId: 11, name: 'Hebei', countryId: 'CHN' },
    { stateId: 12, name: 'Jiangsu', countryId: 'CHN' },
    { stateId: 14, name: 'New Jersey', countryId: 'USA' },
    { stateId: 15, name: 'Massachusetts', countryId: 'USA' },
    { stateId: 16, name: 'Connecticut', countryId: 'USA' },
    { stateId: 17, name: 'Guangdong', countryId: 'CHN' },
    { stateId: 19, name: 'Florida', countryId: 'USA' },
    { stateId: 24, name: 'Texas', countryId: 'USA' },
    { stateId: 28, name: 'Armed Forces US', countryId: 'USA' },
    { stateId: 32, name: 'Tennessee', countryId: 'USA' },
    { stateId: 33, name: 'Kentucky', countryId: 'USA' },
    { stateId: 34, name: 'Ile-de-France', countryId: 'FRA' },
    { stateId: 35, name: 'Georgia', countryId: 'USA' },
    { stateId: 37, name: 'Rio de Janeiro', countryId: 'BRA' },
    { stateId: 44, name: 'Illinois', countryId: 'USA' },
    { stateId: 46, name: 'Ceara', countryId: 'BRA' },
    { stateId: 47, name: 'Colorado', countryId: 'USA' },
    { stateId: 48, name: 'Zhejiang', countryId: 'CHN' },
    { stateId: 49, name: 'Utah', countryId: 'USA' },
    { stateId: 52, name: 'Liaoning', countryId: 'CHN' },
    { stateId: 56, name: 'Haryana', countryId: 'IND' },
    { stateId: 57, name: 'Maryland', countryId: 'USA' },
    { stateId: 62, name: 'Shanghai', countryId: 'CHN' },
    { stateId: 64, name: 'Tianjin', countryId: 'CHN' },
    { stateId: 72, name: 'South Carolina', countryId: 'USA' },
    { stateId: 73, name: 'Montana', countryId: 'USA' },
    { stateId: 76, name: 'Louisiana', countryId: 'USA' },
    { stateId: 77, name: 'Fujian', countryId: 'CHN' },
    { stateId: 78, name: 'Santa Catarina', countryId: 'BRA' },
    { stateId: 80, name: 'Espirito Santo', countryId: 'BRA' },
    { stateId: 84, name: 'Washington', countryId: 'USA' },
    { stateId: 85, name: 'Andhra Pradesh', countryId: 'IND' },
    { stateId: 87, name: 'Pennsylvania', countryId: 'USA' },
    { stateId: 90, name: 'Guangxi', countryId: 'CHN' },
    { stateId: 93, name: 'North Carolina', countryId: 'USA' },
    { stateId: 94, name: 'Shandong', countryId: 'CHN' },
    { stateId: 97, name: 'Chongqing', countryId: 'CHN' },
    { stateId: 98, name: 'Michigan', countryId: 'USA' },
    { stateId: 99, name: 'Hubei', countryId: 'CHN' },
    { stateId: 100, name: 'Delhi', countryId: 'IND' },
    { stateId: 101, name: 'Arkansas', countryId: 'USA' },
    { stateId: 107, name: 'Wisconsin', countryId: 'USA' },
    { stateId: 112, name: 'Midi-Pyrenees', countryId: 'FRA' },
    { stateId: 116, name: 'Picardie', countryId: 'FRA' },
    { stateId: 121, name: 'Bahia', countryId: 'BRA' },
    { stateId: 123, name: 'Heilongjiang', countryId: 'CHN' },
    { stateId: 128, name: 'Tamil Nadu', countryId: 'IND' },
    { stateId: 129, name: 'Ohio', countryId: 'USA' },
    { stateId: 132, name: 'New Mexico', countryId: 'USA' },
    { stateId: 133, name: 'Kansas', countryId: 'USA' },
    { stateId: 136, name: 'Oregon', countryId: 'USA' },
    { stateId: 138, name: 'Uttar Pradesh', countryId: 'IND' },
    { stateId: 140, name: 'Nebraska', countryId: 'USA' },
    { stateId: 143, name: 'West Virginia', countryId: 'USA' },
    { stateId: 144, name: 'Virginia', countryId: 'USA' },
    { stateId: 145, name: 'Missouri', countryId: 'USA' },
    { stateId: 148, name: 'Mississippi', countryId: 'USA' },
    { stateId: 151, name: 'Rhode Island', countryId: 'USA' },
    { stateId: 155, name: 'Sao Paulo', countryId: 'BRA' },
    { stateId: 156, name: 'Shanxi', countryId: 'CHN' },
    { stateId: 160, name: 'Karnataka', countryId: 'IND' },
    { stateId: 161, name: 'Hunan', countryId: 'CHN' },
    { stateId: 163, name: 'Indiana', countryId: 'USA' },
    { stateId: 164, name: 'Oklahoma', countryId: 'USA' },
    { stateId: 175, name: 'Minnesota', countryId: 'USA' },
    { stateId: 176, name: 'Alabama', countryId: 'USA' },
    { stateId: 178, name: 'Hainan', countryId: 'CHN' },
    { stateId: 181, name: 'Arizona', countryId: 'USA' },
    { stateId: 182, name: 'Sichuan', countryId: 'CHN' },
    { stateId: 186, name: 'South Dakota', countryId: 'USA' },
    { stateId: 187, name: 'Maharashtra', countryId: 'IND' },
    { stateId: 192, name: 'Nevada', countryId: 'USA' },
    { stateId: 196, name: 'Henan', countryId: 'CHN' },
    { stateId: 206, name: 'Kerala', countryId: 'IND' },
    { stateId: 215, name: 'New Hampshire', countryId: 'USA' },
    { stateId: 218, name: 'Maine', countryId: 'USA' },
    { stateId: 220, name: 'Hawaii', countryId: 'USA' },
    { stateId: 225, name: 'Chhattisgarh', countryId: 'IND' },
    { stateId: 236, name: 'Anhui', countryId: 'CHN' },
    { stateId: 249, name: 'District of Columbia', countryId: 'USA' },
    { stateId: 254, name: 'Delaware', countryId: 'USA' },
    { stateId: 258, name: 'West Bengal', countryId: 'IND' },
    { stateId: 268, name: 'Shaanxi', countryId: 'CHN' },
    { stateId: 274, name: 'Madhya Pradesh', countryId: 'IND' },
    { stateId: 284, name: 'Gujarat', countryId: 'IND' },
    { stateId: 296, name: 'Franche-Comte', countryId: 'FRA' },
    { stateId: 305, name: 'Idaho', countryId: 'USA' },
    { stateId: 306, name: 'Rajasthan', countryId: 'IND' },
    { stateId: 307, name: 'Nei Mongol', countryId: 'CHN' },
    { stateId: 315, name: 'Alsace', countryId: 'FRA' },
    { stateId: 317, name: 'Orissa', countryId: 'IND' },
    { stateId: 334, name: 'Jilin', countryId: 'CHN' },
    { stateId: 355, name: 'Jharkhand', countryId: 'IND' },
    { stateId: 363, name: 'Chandigarh', countryId: 'IND' },
    { stateId: 377, name: 'Punjab', countryId: 'IND' },
    { stateId: 409, name: 'Languedoc-Roussillon', countryId: 'FRA' },
    { stateId: 416, name: 'Assam', countryId: 'IND' },
    { stateId: 431, name: 'Centre', countryId: 'FRA' },
    { stateId: 469, name: 'Champagne-Ardenne', countryId: 'FRA' },
    { stateId: 471, name: 'Bretagne', countryId: 'FRA' },
    { stateId: 544, name: 'Rhone-Alpes', countryId: 'FRA' },
    { stateId: 555, name: 'Nord-Pas-de-Calais', countryId: 'FRA' },
    { stateId: 556, name: 'Lorraine', countryId: 'FRA' },
    { stateId: 561, name: 'Rio Grande do Sul', countryId: 'BRA' },
    { stateId: 563, name: 'Provence-Alpes-Cote d\'Azur', countryId: 'FRA' },
    { stateId: 586, name: 'Minas Gerais', countryId: 'BRA' },
    { stateId: 598, name: 'Limousin', countryId: 'FRA' },
    { stateId: 600, name: 'Guizhou', countryId: 'CHN' },
    { stateId: 635, name: 'Haute-Normandie', countryId: 'FRA' },
    { stateId: 649, name: 'Poitou-Charentes', countryId: 'FRA' },
    { stateId: 667, name: 'Wyoming', countryId: 'USA' },
    { stateId: 676, name: 'Daman and Diu', countryId: 'IND' },
    { stateId: 701, name: 'Para', countryId: 'BRA' },
    { stateId: 708, name: 'Basse-Normandie', countryId: 'FRA' },
    { stateId: 728, name: 'Bihar', countryId: 'IND' },
    { stateId: 729, name: 'Aquitaine', countryId: 'FRA' },
    { stateId: 773, name: 'Parana', countryId: 'BRA' },
    { stateId: 798, name: 'Auvergne', countryId: 'FRA' },
    { stateId: 808, name: 'Pernambuco', countryId: 'BRA' },
    { stateId: 822, name: 'Pays de la Loire', countryId: 'FRA' },
    { stateId: 838, name: 'Amazonas', countryId: 'BRA' },
    { stateId: 842, name: 'Distrito Federal', countryId: 'BRA' },
    { stateId: 924, name: 'North Dakota', countryId: 'USA' },
    { stateId: 937, name: 'Bourgogne', countryId: 'FRA' },
    { stateId: 959, name: 'Vermont', countryId: 'USA' },
    { stateId: 970, name: 'Goias', countryId: 'BRA' },
    { stateId: 1008, name: 'Himachal Pradesh', countryId: 'IND' },
    { stateId: 1011, name: 'Sergipe', countryId: 'BRA' },
    { stateId: 1061, name: 'Alaska', countryId: 'USA' },
    { stateId: 1102, name: 'Mato Grosso do Sul', countryId: 'BRA' },
    { stateId: 1178, name: 'Yunnan', countryId: 'CHN' },
    { stateId: 1200, name: 'Uttarakhand', countryId: 'IND' },
    { stateId: 1203, name: 'Meghalaya', countryId: 'IND' },
    { stateId: 1231, name: 'Jiangxi', countryId: 'CHN' },
    { stateId: 1269, name: 'Rio Grande do Norte', countryId: 'BRA' },
    { stateId: 1293, name: 'Paraiba', countryId: 'BRA' },
    { stateId: 1297, name: 'Piaui', countryId: 'BRA' },
    { stateId: 1310, name: 'Gansu', countryId: 'CHN' },
    { stateId: 1312, name: 'Jammu and Kashmir', countryId: 'IND' },
    { stateId: 1334, name: 'Goa', countryId: 'IND' },
    { stateId: 1335, name: 'Maranhao', countryId: 'BRA' },
    { stateId: 1457, name: 'Mato Grosso', countryId: 'BRA' },
    { stateId: 1483, name: 'Corse', countryId: 'FRA' },
    { stateId: 1568, name: 'Alagoas', countryId: 'BRA' },
    { stateId: 1596, name: 'Puducherry', countryId: 'IND' },
    { stateId: 1654, name: 'Manipur', countryId: 'IND' },
    { stateId: 1673, name: 'Tocantins', countryId: 'BRA' },
    { stateId: 1714, name: 'Roraima', countryId: 'BRA' },
    { stateId: 1723, name: 'Rondonia', countryId: 'BRA' },
    { stateId: 1736, name: 'Xizang', countryId: 'CHN' },
    { stateId: 1741, name: 'Ningxia', countryId: 'CHN' },
    { stateId: 1751, name: 'Xinjiang', countryId: 'CHN' },
    { stateId: 1753, name: 'Qinghai', countryId: 'CHN' },
    { stateId: 1791, name: 'Mizoram', countryId: 'IND' },
    { stateId: 1846, name: 'Dadra and Nagar Haveli', countryId: 'IND' },
    { stateId: 1874, name: 'Arunachal Pradesh', countryId: 'IND' },
    { stateId: 1918, name: 'Tripura', countryId: 'IND' },
    { stateId: 2113, name: 'Amapa', countryId: 'BRA' },
    { stateId: 2116, name: 'Acre', countryId: 'BRA' },
    { stateId: 2320, name: 'Sikkim', countryId: 'IND' },
    { stateId: 2370, name: 'Nagaland', countryId: 'IND' },
    { stateId: 2594, name: 'Andaman and Nicobar Islands', countryId: 'IND' },
    { stateId: 2973, name: 'Shandong Sheng', countryId: 'CHN' },
    { stateId: 2977, name: 'Henan Sheng', countryId: 'CHN' },
    { stateId: 2981, name: 'Shanghai Shi', countryId: 'CHN' },
    { stateId: 2982, name: 'Zhejiang Sheng', countryId: 'CHN' },
    { stateId: 2989, name: 'Sichuan Sheng', countryId: 'CHN' },
    { stateId: 2992, name: 'Tianjin Shi', countryId: 'CHN' },
    { stateId: 2994, name: 'Guangxi Zhuangzu Zizhiqu', countryId: 'CHN' },
    { stateId: 2995, name: 'Beijing Shi', countryId: 'CHN' },
    { stateId: 3001, name: 'State of Gujarat', countryId: 'IND' },
    { stateId: 3003, name: 'Jiangsu Sheng', countryId: 'CHN' },
    { stateId: 3009, name: 'National Capital Territory of Delhi', countryId: 'IND' },
    { stateId: 3024, name: 'Jilin Sheng', countryId: 'CHN' },
    { stateId: 3034, name: 'Lower Normandy', countryId: 'FRA' },
    { stateId: 3040, name: 'Odisha', countryId: 'IND' },
    { stateId: 3043, name: 'Heilongjiang Sheng', countryId: 'CHN' },
    { stateId: 3050, name: 'Anhui Sheng', countryId: 'CHN' },
    { stateId: 3060, name: 'Telangana', countryId: 'IND' },
    { stateId: 3100, name: 'Jiangxi Sheng', countryId: 'CHN' },
    { stateId: 3120, name: 'Federal District', countryId: 'BRA' },
    { stateId: 3128, name: 'Chongqing Shi', countryId: 'CHN' },
    { stateId: 3152, name: 'Shanxi Sheng', countryId: 'CHN' },
    { stateId: 3177, name: 'Guizhou Sheng', countryId: 'CHN' },
    { stateId: 3192, name: 'Gansu Sheng', countryId: 'CHN' },
    { stateId: 3203, name: 'Inner Mongolia', countryId: 'CHN' },
    { stateId: 3212, name: 'Xinjiang Uygur Zizhiqu', countryId: 'CHN' },
    { stateId: 3225, name: 'Tibet Autonomous Region', countryId: 'CHN' },
    { stateId: 3260, name: 'State of Andhra Pradesh', countryId: 'IND' },
    { stateId: 3282, name: 'State of Punjab', countryId: 'IND' },
    { stateId: 3289, name: 'State of Himachal Pradesh', countryId: 'IND' },
    { stateId: 3290, name: 'Kashmir', countryId: 'IND' },
    { stateId: 3334, name: 'State of Chhattisgarh', countryId: 'IND' },
    { stateId: 3339, name: 'State of Jharkhand', countryId: 'IND' },
    { stateId: 3421, name: 'Brittany', countryId: 'FRA' },
    { stateId: 3533, name: 'State of Rājasthān', countryId: 'IND' },
    { stateId: 3582, name: 'Upper Normandy', countryId: 'FRA' },
    { stateId: 3747, name: 'State of Assam', countryId: 'IND' },
    { stateId: 3778, name: 'Corsica', countryId: 'FRA' },
    { stateId: 3835, name: 'Qinghai Sheng', countryId: 'CHN' },
    { stateId: 3842, name: 'Union Territory of Puducherry', countryId: 'IND' },
    { stateId: 4017, name: 'State of Tripura', countryId: 'IND' },
    { stateId: 4791, name: 'Guangxi Zhuang Autonomous Region', countryId: 'CHN' },
    { stateId: 4793, name: 'Seine-Maritime', countryId: 'FRA' },
    { stateId: 4794, name: 'Hérault', countryId: 'FRA' },
    { stateId: 4795, name: 'Bas-Rhin', countryId: 'FRA' },
    { stateId: 4800, name: 'Xinjiang Uyghur Autonomous Region', countryId: 'CHN' },
    { stateId: 4801, name: 'Oise', countryId: 'FRA' },
    { stateId: 4804, name: 'Marne', countryId: 'FRA' },
    { stateId: 4805, name: 'Inner Mongolia Autonomous Region', countryId: 'CHN' },
    { stateId: 4807, name: 'Orne', countryId: 'FRA' },
    { stateId: 4808, name: 'Isère', countryId: 'FRA' },
    { stateId: 4810, name: 'Gironde', countryId: 'FRA' },
    { stateId: 4811, name: 'North', countryId: 'FRA' },
    { stateId: 4813, name: 'Charente-Maritime', countryId: 'FRA' },
    { stateId: 4814, name: 'Rhône', countryId: 'FRA' },
    { stateId: 4815, name: 'Ariège', countryId: 'FRA' },
    { stateId: 4816, name: 'Haute-Savoie', countryId: 'FRA' },
    { stateId: 4817, name: 'Somme', countryId: 'FRA' },
    { stateId: 4818, name: 'Vosges', countryId: 'FRA' },
    { stateId: 4819, name: 'Meurthe et Moselle', countryId: 'FRA' },
    { stateId: 4820, name: 'Upper Garonne', countryId: 'FRA' },
    { stateId: 4821, name: 'Pyrénées-Orientales', countryId: 'FRA' },
    { stateId: 4823, name: 'Puy-de-Dôme', countryId: 'FRA' },
    { stateId: 4824, name: 'Aude', countryId: 'FRA' },
    { stateId: 4825, name: 'Calvados', countryId: 'FRA' },
    { stateId: 4826, name: 'Pas-de-Calais', countryId: 'FRA' },
    { stateId: 4827, name: 'Charente', countryId: 'FRA' },
    { stateId: 4828, name: 'Haute-Vienne', countryId: 'FRA' },
    { stateId: 4830, name: 'Haut-Rhin', countryId: 'FRA' },
    { stateId: 4831, name: 'Landes', countryId: 'FRA' },
    { stateId: 4832, name: 'Loire', countryId: 'FRA' },
    { stateId: 4833, name: 'Cote d\'Or', countryId: 'FRA' },
    { stateId: 4834, name: 'Savoy', countryId: 'FRA' },
    { stateId: 4835, name: 'Moselle', countryId: 'FRA' },
    { stateId: 4836, name: 'Saône-et-Loire', countryId: 'FRA' },
    { stateId: 4837, name: 'Doubs', countryId: 'FRA' },
    { stateId: 4838, name: 'Gard', countryId: 'FRA' },
    { stateId: 4839, name: 'Aube', countryId: 'FRA' },
    { stateId: 4842, name: 'Manche', countryId: 'FRA' },
    { stateId: 4843, name: 'Jura', countryId: 'FRA' },
    { stateId: 4844, name: 'Vienne', countryId: 'FRA' },
    { stateId: 4845, name: 'Hautes-Pyrénées', countryId: 'FRA' },
    { stateId: 4847, name: 'Ardèche', countryId: 'FRA' },
    { stateId: 4848, name: 'Lozère', countryId: 'FRA' },
    { stateId: 4849, name: 'Deux-Sèvres', countryId: 'FRA' },
    { stateId: 4850, name: 'Ningsia Hui Autonomous Region', countryId: 'CHN' },
    { stateId: 4852, name: 'Eure', countryId: 'FRA' },
    { stateId: 4853, name: 'Aisne', countryId: 'FRA' },
    { stateId: 4854, name: 'Allier', countryId: 'FRA' },
    { stateId: 4856, name: 'Ain', countryId: 'FRA' },
    { stateId: 4857, name: 'Territoire de Belfort', countryId: 'FRA' },
    { stateId: 4858, name: 'Lot-et-Garonne', countryId: 'FRA' },
    { stateId: 4859, name: 'Pyrénées-Atlantiques', countryId: 'FRA' },
    { stateId: 4860, name: 'Haute-Saône', countryId: 'FRA' },
    { stateId: 4862, name: 'Dordogne', countryId: 'FRA' },
    { stateId: 4865, name: 'Gers', countryId: 'FRA' },
    { stateId: 4868, name: 'Nièvre', countryId: 'FRA' },
    { stateId: 4871, name: 'Haute-Loire', countryId: 'FRA' },
    { stateId: 4872, name: 'Meuse', countryId: 'FRA' },
    { stateId: 4876, name: 'Haute-Marne', countryId: 'FRA' },
    { stateId: 4877, name: 'Ardennes', countryId: 'FRA' },
    { stateId: 4878, name: 'Lot', countryId: 'FRA' },
    { stateId: 4881, name: 'Drôme', countryId: 'FRA' },
    { stateId: 4884, name: 'Aveyron', countryId: 'FRA' },
    { stateId: 4886, name: 'Tarn', countryId: 'FRA' },
    { stateId: 4892, name: 'Guangdong', countryId: 'USA' },
    { stateId: 4893, name: 'Yonne', countryId: 'FRA' },
    { stateId: 4895, name: 'Tarn-et-Garonne', countryId: 'FRA' },
    { stateId: 4896, name: 'Cantal', countryId: 'FRA' },
    { stateId: 4898, name: 'Corrèze', countryId: 'FRA' },
    { stateId: 4903, name: 'Creuse', countryId: 'FRA' },
    { stateId: 5042, name: 'Laccadives', countryId: 'IND' },
    { stateId: 5106, name: 'Nouvelle-Aquitaine', countryId: 'FRA' },
    { stateId: 5107, name: 'Hauts-de-France', countryId: 'FRA' },
    { stateId: 5119, name: 'Bourgogne-Franche-Comte', countryId: 'FRA' },
    { stateId: 5122, name: 'Occitanie', countryId: 'FRA' },
    { stateId: 5124, name: 'Normandy', countryId: 'FRA' },
    { stateId: 5126, name: 'Auvergne-Rhone-Alpes', countryId: 'FRA' },
    { stateId: 5129, name: 'Grand-Est', countryId: 'FRA' },
    { stateId: 5151, name: 'Tibet', countryId: 'CHN' },
    { stateId: 5243, name: 'Andaman and Nicobar', countryId: 'IND' }
];


StateModel.insertMany(docs, (err, docs) => {
    if (err) {
        console.error('StateModel.insertMany: Failed', err);
        return false;
    }
    console.log('%d States added successfully!!!', docs.length);
});